# Generated by Django 4.1.7 on 2023-03-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0004_loan_transactionrecord_payment_emi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
